// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// group_by_range_cpp
IntegerVector group_by_range_cpp(NumericVector x, double max_range);
RcppExport SEXP _clinpubr_group_by_range_cpp(SEXP xSEXP, SEXP max_rangeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type max_range(max_rangeSEXP);
    rcpp_result_gen = Rcpp::wrap(group_by_range_cpp(x, max_range));
    return rcpp_result_gen;
END_RCPP
}
// mov_sort_cpp
IntegerVector mov_sort_cpp(IntegerVector ids0, IntegerMatrix pos);
RcppExport SEXP _clinpubr_mov_sort_cpp(SEXP ids0SEXP, SEXP posSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type ids0(ids0SEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type pos(posSEXP);
    rcpp_result_gen = Rcpp::wrap(mov_sort_cpp(ids0, pos));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_clinpubr_group_by_range_cpp", (DL_FUNC) &_clinpubr_group_by_range_cpp, 2},
    {"_clinpubr_mov_sort_cpp", (DL_FUNC) &_clinpubr_mov_sort_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_clinpubr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
