# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Group Sorted Vector by Range
#'
#' Divide a sorted numeric vector into groups such that
#' \code{max(x[group]) - min(x[group]) <= max_range}.
#'
#' @param x A sorted numeric vector, Date vector, or POSIXt vector.
#' @param max_range A non-negative numeric threshold for the within-group range.
#' @return An IntegerVector of group IDs (1-indexed).
#' @export
group_by_range_cpp <- function(x, max_range) {
    .Call(`_clinpubr_group_by_range_cpp`, x, max_range)
}

