# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Group Sorted Vector by Range
#'
#' Divide a sorted numeric vector into groups such that
#' \code{max(x[group]) - min(x[group]) <= max_range}.
#'
#' @param x A sorted numeric vector, Date vector, or POSIXt vector.
#' @param max_range A non-negative numeric threshold for the within-group range.
#' @return An IntegerVector of group IDs (1-indexed).
#' @export
group_by_range_cpp <- function(x, max_range) {
    .Call(`_clinpubr_group_by_range_cpp`, x, max_range)
}

#' Vote-based Ordered Vector Merge (C++ core)
#'
#' Reproduces the exact swap-order semantics of
#' \code{clinpubr::merge_ordered_vectors()}: for each pair \code{(x[i], x[j])},
#' count in how many vectors \code{x[i]} precedes/follows \code{x[j]} (by first
#' occurrence); swap when the element precedes in fewer vectors. Swapping
#' updates \code{x[i]} and comparison continues, matching the original
#' bubble-style sort exactly.
#'
#' @param ids0 IntegerVector of 0-based element IDs (in initial order).
#' @param pos IntegerMatrix of shape \code{[n x K]}, column-major, where
#'   \code{pos[e, k]} is the 1-based first-occurrence position of element \code{e}
#'   in vector \code{k}, and \code{0} means not present.
#' @return An IntegerVector of 0-based IDs in merged order.
mov_sort_cpp <- function(ids0, pos) {
    .Call(`_clinpubr_mov_sort_cpp`, ids0, pos)
}

